pipeline {
  agent any
  environment {
    VAR1 = 'VAL1'
    M2_SETTINGS = 'MAVEN_HOME'
    FAMILY = "CAVE"
    ADDRESS = "FOREST LAKE"
  }
  parameters {
    string defaultValue: 'andrews_proxy_file.csv', description: 'Proxy file name', name: 'GEN_PROXY_FILE'
      choice choices: ['D1', 'D2'], description: 'CICS Envrironment', name: 'GEN_ENVIRONMENT'
  }

  stages {
    stage('Hello') {
       steps {
            echo 'Hello World'
       }
    }

    stage('run-ant-script') {
        steps {
            echo 'Build step'
            withAnt(installation: 'ANT-1.10.13', jdk: 'OPENJDK-17') {
                withEnv(['TRIAL_BUILD=Y', "PROXY_FILE=${params.GEN_PROXY_FILE}",
                         "GEN_ENVIRONMENT=${params.GEN_ENVIRONMENT}"]) {
                    bat 'ant -buildfile ./ant-script-demo/build-hello.xml'
                }
            }
        }
    }
  }
}